### ISSUE TITLE
Cannot Install From Github

### ISSUE THREAD

**Issue by lmusolff** [sergiocorreia/ppmlhdfe#1]
I had the old files you e-mailed me, so I thought I'd upgrade to this new version. But attempting to execute the installation instructions from the readme yields:

```

. clear

. cap ado uninstall ppmlhdfe

. net install ppmlhdfe, from("https://raw.githubusercontent.com/sergiocorreia/ppmlhdfe/master/src/")
https://raw.githubusercontent.com/sergiocorreia/ppmlhdfe/master/src/ either
  1)  is not a valid URL, or
  2)  could not be contacted, or
  3)  is not a Stata download site (has no stata.toc file).

current site is still https://raw.githubusercontent.com/sergiocorreia/reghdfe/master/src/
--Break--
r(1);

. 

```

I was able to execute the same commands to (re-)install ftools and gtools from Github without any problems directly before this. I've also verified that I can access "https://raw.githubusercontent.com/sergiocorreia/ppmlhdfe/master/src/stata.toc" with a browser. Any clue what might be going on? I am using Stata/MP 13.1 for Mac (64-bit Intel). 

P.S. Off-topic, but thank you so much for this project. PPMLHDFE has been a big time-saver for me -- and even more important that it runs regressions that previously just would not run! Really a great piece of software.

**Comment by sergiocorreia** [comment]
You got me scratching my head for a while, but I think I got the answer in a bug report to StataCorp:

https://www.statalist.org/forums/forum/general-stata-discussion/general/1292378-https-in-stata-13

> The issue Sergiy Radyakin described exists in both Stata 13 and Stata 14. We have looked into the problem and it appears to be triggered by the content buffer containing less than 100 bytes. We will get it fixed in both Stata 13 and Stata 14 and make it available through normal Stata updates.

So it seems that it should be fixed by updating Stata.

I'll also add some filler text to the `.toc` file to prevent the problem happening again.

**Comment by sergiocorreia** [comment]
Just pushed an updated that added more text to the `stata.toc` file. Let me know if the problem still occurs, and if so, feel free to reopen the issue.

**Comment by lmusolff** [comment]
Works like a charm now. Thanks!
