### ISSUE TITLE
Unable to run Wild Bootstrap

### ISSUE THREAD

**Issue by caiopasc** [sergiocorreia/ppmlhdfe#10]
Dear Sergio,

Thanks for this package, it's a real time saver.

I'm trying to use _ppmlhdfe_ clustering on month of birth. Because I only have 12 groups, I want to use **wild boostrapping** for my inference, but upon running
`boottest treat, boottype(wild)`
I get the message:
`boottype(wild) not accepted after GMM or Maximum Likelihood-based estimation.`

Do you know if that's an issue with ppmlhdfe _per se_ or perhaps with boottest?

Thank you in advance!

**Comment by ArthurHowardMorris** [comment]
For anyone that googles their way here: `boottest, boottype(wild)` is not allowed after ML (or pseudo-ML) estimation. Consider `boottype(score)`
