### ISSUE TITLE
Does not run with Linux OS

### ISSUE THREAD

**Issue by EconJoe** [sergiocorreia/ppmlhdfe#3]
Hi Sergio,

Thanks for developing such a great command! It runs perfectly on my Desktop computer, which has a Windows 10 OS. However, when I try to run it on the NBER cluster (Redhat Linux OS), I get the following error message:

accuracy not found in class FixedEffects
(113 lines skipped)
(error occurred while loading ppmlhdfe.ado)
r(3000);

I am happy to provide you with any other info you might want.

Joe Staudt

**Comment by sergiocorreia** [comment]
Hi Joe,

The fixedeffects class is part of reghdfe, so the first thing I should check is that you have the latest version installed (of both packages, as well as of ftools)

Also, I work with ppmlhdfe on Linux so that shouldn't be an issue

**Comment by EconJoe** [comment]
Hi Sergio,

You are exactly right. I had the latest versions installed in my PLUS directory, which lead to my confusion. However, there is another directory for ado files on the NBER cluster, which is searched first by Stata, and did not have the latest versions. Once these were updated by the admin, everything worked perfectly.

Thanks again for such a useful command!

Joe
