### ISSUE TITLE
Error occurred in loading ppmlhdfe.ado

### ISSUE THREAD

**Issue by mts918** [sergiocorreia/ppmlhdfe#5]
Hi all, 

I am seeing the following error message when trying to run ppmlhdfe : 

![image](https://user-images.githubusercontent.com/65122190/81502176-9d6f5100-92dc-11ea-91a3-eeec21286a06.png)

Would you have advice how to proceed?  Both ftools and reghdfe are installed; reghdfe has been working fine.  

Thank you in advance for your help.

**Comment by sergiocorreia** [comment]
you problably need the latest versionnof reghdfe

**Comment by mts918** [comment]
Thank you very much
